language: objective-c
osx_image: xcode9.3beta
branches:
  only:
    - travis
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT="Bruno.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="Bruno"
  - EXAMPLE_SCHEME="Example"
  - CONFIGURATION="Release"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "OS=11.2,name=iPhone 6" -configuration "$CONFIGURATION" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
