language: swift
osx_image: xcode9.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT="Bruno.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="Bruno"
  - EXAMPLE_SCHEME="Example"
  - CONFIGURATION="Debug"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2' -configuration "$CONFIGURATION" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios -J 'bruno-ios'